import { toPng } from "html-to-image";

// @ts-ignore
import jsPDF from "jspdf";

export const exportToPDF = async (
  elementId: string,
  fileName: string,
  title: string
) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      console.error(`Element with id ${elementId} not found`);
      return;
    }

    // Capture the element as image
    const imgData = await toPng(element, {
      quality: 0.95,
      pixelRatio: 2,
    });

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const imgWidth = 210; // A4 width in mm
    const img = new Image();
    img.src = imgData;

    img.onload = () => {
      const imgHeight = (img.height * imgWidth) / img.width;
      let heightLeft = imgHeight;
      let position = 0;

      // Add title
      pdf.setFontSize(16);
      pdf.text(title, 15, 15);
      pdf.setFontSize(10);
      pdf.text(`Generated on: ${new Date().toLocaleString()}`, 15, 25);

      // Add images
      position = 35;
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pdf.internal.pageSize.getHeight() - 35;

      while (heightLeft >= 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= pdf.internal.pageSize.getHeight();
      }

      pdf.save(`${fileName}-${new Date().getTime()}.pdf`);
    };
  } catch (error) {
    console.error("PDF export failed:", error);
    throw error;
  }
};

export const exportDataToPDF = async (
  data: any[],
  columns: { label: string; key: string }[],
  fileName: string,
  title: string,
  options?: {
    subtitle?: string;
    generatedBy?: string;
    filters?: string[];
    summary?: Array<{ label: string; value: string | number }>;
    maxCellChars?: number;
    logoPath?: string;
    footerSignature?: string;
    footerNote?: string;
  }
) => {
  try {
    const pdf = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    const marginX = 12;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const pageHeight = pdf.internal.pageSize.getHeight();
    const maxCellChars = options?.maxCellChars ?? 38;

    const loadLogoDataUrl = async (logoPath: string) => {
      return await new Promise<string>((resolve, reject) => {
        const image = new Image();
        image.crossOrigin = "anonymous";
        image.onload = () => {
          try {
            const scale = 4;
            const canvas = document.createElement("canvas");
            canvas.width = image.naturalWidth * scale;
            canvas.height = image.naturalHeight * scale;
            const context = canvas.getContext("2d");

            if (!context) {
              reject(new Error("Canvas context unavailable"));
              return;
            }

            context.imageSmoothingEnabled = true;
            context.imageSmoothingQuality = "high";
            context.drawImage(image, 0, 0, canvas.width, canvas.height);
            resolve(canvas.toDataURL("image/png"));
          } catch (error) {
            reject(error);
          }
        };
        image.onerror = () => reject(new Error("Failed to load logo"));
        image.src = logoPath;
      });
    };

    let logoDataUrl: string | null = null;
    try {
      logoDataUrl = await loadLogoDataUrl(options?.logoPath || "/logo.svg");
    } catch {
      logoDataUrl = null;
    }

    const drawPageHeader = (isFirstPage: boolean) => {
      // Title band
      pdf.setFillColor(30, 41, 59);
      pdf.rect(0, 0, pageWidth, 22, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFont(undefined, "bold");
      pdf.setFontSize(14);
      pdf.text(title, marginX, 13);

      pdf.setFont(undefined, "normal");
      pdf.setFontSize(9);
      pdf.text(
        `Generated: ${new Date().toLocaleString()}`,
        pageWidth - (logoDataUrl ? 34 : marginX),
        13,
        { align: "right" }
      );

      if (logoDataUrl) {
        try {
          pdf.addImage(logoDataUrl, "PNG", pageWidth - 28, 4.5, 14, 14);
        } catch {
          // Logo is optional; continue without failing export.
        }
      }

      let y = 28;

      if (isFirstPage && options?.subtitle) {
        pdf.setTextColor(51, 65, 85);
        pdf.setFontSize(10);
        pdf.text(options.subtitle, marginX, y);
        y += 6;
      }

      if (isFirstPage && options?.generatedBy) {
        pdf.setTextColor(71, 85, 105);
        pdf.setFontSize(9);
        pdf.text(`Generated by: ${options.generatedBy}`, marginX, y);
        y += 5;
      }

      if (isFirstPage && options?.filters?.length) {
        pdf.setTextColor(100, 116, 139);
        pdf.setFontSize(8.5);
        pdf.text(`Filters: ${options.filters.join(" | ")}`, marginX, y);
        y += 6;
      }

      if (isFirstPage && options?.summary?.length) {
        const summaryItems = options.summary.slice(0, 5);
        const gap = 3;
        const cardWidth =
          (pageWidth - marginX * 2 - gap * (summaryItems.length - 1)) /
          summaryItems.length;

        summaryItems.forEach((item, idx) => {
          const cardX = marginX + idx * (cardWidth + gap);
          pdf.setFillColor(241, 245, 249);
          pdf.roundedRect(cardX, y, cardWidth, 15, 1.8, 1.8, "F");
          pdf.setTextColor(100, 116, 139);
          pdf.setFontSize(7.5);
          pdf.text(item.label, cardX + 2, y + 5);
          pdf.setTextColor(15, 23, 42);
          pdf.setFont(undefined, "bold");
          pdf.setFontSize(10);
          pdf.text(String(item.value), cardX + 2, y + 11);
          pdf.setFont(undefined, "normal");
        });

        y += 20;
      }

      return y;
    };

    const drawPageFooter = (pageNo: number, totalPages: number) => {
      const signature = options?.footerSignature || "Prepared for CivicPulse Admin";
      const footerNote =
        options?.footerNote || "Digitally generated report - Confidential";

      pdf.setTextColor(100, 116, 139);
      pdf.setFontSize(8);
      pdf.setFont(undefined, "bold");
      pdf.text(signature, marginX, pageHeight - 6);

      pdf.setFont(undefined, "normal");
      pdf.text(footerNote, marginX, pageHeight - 2.5);
      pdf.text(`Page ${pageNo} of ${totalPages}`, pageWidth - marginX, pageHeight - 2.5, {
        align: "right",
      });
    };

    // Create table data
    const tableData = data.map((row) =>
      columns.map((col) => {
        const value = row[col.key];
        if (value === null || value === undefined) return "";
        if (typeof value === "object") return JSON.stringify(value);
        return String(value).substring(0, maxCellChars);
      })
    );

    const columnHeaders = columns.map((col) => col.label);

    const availableWidth = pageWidth - marginX * 2;

    // Build adaptive column widths so longer labels/values get more room.
    const sampledRows = tableData.slice(0, 50);
    const rawWeights = columns.map((_, idx) => {
      const headerLen = columnHeaders[idx].length;
      const longestCell = sampledRows.reduce((maxLen, row) => {
        const len = (row[idx] || "").length;
        return len > maxLen ? len : maxLen;
      }, 0);

      return Math.max(8, Math.min(28, Math.max(headerLen, longestCell)));
    });

    const minColWidth = 20;
    const weightedWidth = availableWidth - minColWidth * columns.length;
    const totalWeight = rawWeights.reduce((sum, w) => sum + w, 0) || 1;

    const columnWidths = rawWeights.map(
      (w) => minColWidth + (w / totalWeight) * Math.max(0, weightedWidth)
    );

    const columnStarts = columnWidths.reduce<number[]>((starts, width, idx) => {
      if (idx === 0) {
        starts.push(marginX);
      } else {
        starts.push(starts[idx - 1] + columnWidths[idx - 1]);
      }
      return starts;
    }, []);

    const lineHeight = 3.8;

    const drawTableHeader = (yPosition: number) => {
      pdf.setFont(undefined, "bold");
      pdf.setDrawColor(203, 213, 225);

      const resolvedHeaders = columnHeaders.map(
        (header, idx) => String(header || `Column ${idx + 1}`)
      );
      const headerLines = resolvedHeaders.map((header, idx) =>
        pdf.splitTextToSize(header, columnWidths[idx] - 4)
      );
      const maxHeaderLines = headerLines.reduce(
        (max, lines) => Math.max(max, lines.length),
        1
      );
      const headerHeight = Math.max(9, 4 + maxHeaderLines * lineHeight);

      columnHeaders.forEach((_, idx) => {
        const cellX = columnStarts[idx];
        // Explicit per-cell styling ensures no header can disappear.
        pdf.setFillColor(226, 232, 240);
        pdf.setTextColor(30, 41, 59);
        pdf.rect(cellX, yPosition, columnWidths[idx], headerHeight, "F");
        pdf.rect(cellX, yPosition, columnWidths[idx], headerHeight, "S");
        pdf.text(headerLines[idx], cellX + 2, yPosition + 4.2);
      });

      return yPosition + headerHeight;
    };

    let yPosition = drawPageHeader(true);
    yPosition = drawTableHeader(yPosition);

    pdf.setFont(undefined, "normal");
    pdf.setTextColor(15, 23, 42);

    tableData.forEach((row, rowIdx) => {
      const wrappedCells = row.map((cell, colIdx) =>
        pdf.splitTextToSize(cell, columnWidths[colIdx] - 4)
      );
      const maxLines = wrappedCells.reduce(
        (max, lines) => Math.max(max, lines.length),
        1
      );
      const rowHeight = Math.max(7.5, 3 + maxLines * lineHeight);

      if (yPosition + rowHeight > pageHeight - 10) {
        pdf.addPage();
        yPosition = drawPageHeader(false);
        yPosition = drawTableHeader(yPosition);
        pdf.setFont(undefined, "normal");
        pdf.setTextColor(15, 23, 42);
      }

      if (rowIdx % 2 === 0) {
        pdf.setFillColor(248, 250, 252);
        pdf.rect(marginX, yPosition, availableWidth, rowHeight, "F");
      }

      // Light cell borders improve visual separation and readability.
      pdf.setDrawColor(226, 232, 240);
      wrappedCells.forEach((lines, colIdx) => {
        const cellX = columnStarts[colIdx];
        pdf.rect(cellX, yPosition, columnWidths[colIdx], rowHeight, "S");
        pdf.text(lines, cellX + 2, yPosition + 3.2);
      });

      yPosition += rowHeight;
    });

    const totalPages = pdf.getNumberOfPages();
    for (let pageNo = 1; pageNo <= totalPages; pageNo += 1) {
      pdf.setPage(pageNo);
      drawPageFooter(pageNo, totalPages);
    }

    pdf.save(`${fileName}-${new Date().getTime()}.pdf`);
  } catch (error) {
    console.error("PDF export failed:", error);
    throw error;
  }
};
